

find_package(OpenGL REQUIRED)
if(OPENGL_FOUND)
	set(PROJ_INCLUDE_DIRS ${PROJ_INCLUDE_DIRS} ${OPENGL_INCLUDE_DIR})
	set(PROJ_LIBRARIES ${PROJ_LIBRARIES} ${OPENGL_gl_LIBRARY})
endif()

if(OPENGL_GLU_FOUND)
	set(PROJ_LIBRARIES ${PROJ_LIBRARIES} ${OPENGL_glu_LIBRARY})
endif()


set(TARGET GLFW)
if(WIN32)
	find_package(${TARGET})
	message("${TARGET}_FOUND is ${${TARGET}_FOUND}")
	if(GLFW_FOUND)	
		set(PROJ_INCLUDE_DIRS ${PROJ_INCLUDE_DIRS} ${${TARGET}_INCLUDE_DIRS})
		set(PROJ_LIBRARIES ${PROJ_LIBRARIES} ${${TARGET}_LIBRARIES})
		message("set(PROJ_LIBRARIES ${PROJ_LIBRARIES} ${${TARGET}_LIBRARIES})")
	endif()
elseif(UNIX)
	find_package(PkgConfig REQUIRED)
	pkg_search_module(${TARGET} REQUIRED glfw3)

	set(PROJ_INCLUDE_DIRS ${PROJ_INCLUDE_DIRS} ${${TARGET}_INCLUDE_DIRS})
	set(PROJ_LIBRARIES ${PROJ_LIBRARIES} ${${TARGET}_LIBRARIES} ${${TARGET}_STATIC_LIBRARIES})
endif()


set(MY_CPP_FLAGS "${MY_CPP_FLAGS}")
